spring:
  application:
    name: jpashop
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true    # sout ?? ???
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger ? ???
    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j